### PR TITLE
Configure circle.ci

### PR DESCRIPTION
**Pull request by danimal141**
@iusztin 
I added configuration to use Circle CI. 
I already checked if it worked well and this is the example: https://circleci.com/gh/NEWROPE/scnnr-js/5.

Please review it.

### CODE REVIEW

**Comment by danimal141** [comment]
> Would it be better to add this project to our settings on CircleCi, so we could see the insights generated from the test results?

Sorry, what changes are you requesting?

**Comment by iusztin** [comment]
I meant this: https://circleci.com/build-insights/gh/NEWROPE 
If we add `scnnr-js` as a project, we could see stats about our tests there. Should we add it?

**Comment by danimal141** [comment]
I already added `scnnr-js` as a project, that's why the CI test is running in this PR.

Plus, we can see `NEWROPE/scnnr-js` the insights and the stats are for the master branch. 
So I think if you merge this into the master branch, we can start seeing the stats there.

**Comment by iusztin** [comment]
> I already added scnnr-js as a project, that's why the CI test is running in this PR.

> Plus, we can see NEWROPE/scnnr-js in the insights and the stats are for the master branch.
So I think if you merge this into the master branch, we can start seeing the stats there.

Ah, sorry. I overlooked that the insights depend on the master branch.
Then I agree, I think everything is OK.

**Pull request merged**
