### PR TITLE
Bump mocha from 4.0.1 to 8.1.1

### PR DESCRIPTION
**Pull request by hiroara**
@RobertMaciejewski I made this PR instead of https://github.com/NEWROPE/scnnr-js/pull/37 because the dependabot command doesn't work for some reason 🤔 

Bumps [mocha](https://github.com/mochajs/mocha) from 4.0.1 to 8.1.1.
- [Release notes](https://github.com/mochajs/mocha/releases)
- [Changelog](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md)
- [Commits](https://github.com/mochajs/mocha/compare/v4.0.1...v8.1.1)

I just rebased the branch and applied [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) then the CI build has been passed. I checked the changelog, and I couldn't find any changes that are needed to upgrade mocha.
Please take a look!

### CODE REVIEW

**Review by RobertMaciejewski — APPROVED** [review]
LGTM 👍

**Comment by RobertMaciejewski** [comment]
@hiroara Sorry there are some conflicts! Could you take a look?

**Comment by hiroara** [comment]
> @hiroara Sorry there are some conflicts! Could you take a look?

Ah, OK. Thank you for notifying me!

**Comment by hiroara** [comment]
@RobertMaciejewski I rebased this branch and regenerate the package. Please take a look!

**Pull request merged**
